version: '3.8'
services:
  backend:
    build: backend/
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      FLASK_APP: app
      FLASK_RUN_HOST: 0.0.0.0

  frontend:
    build: frontend/
    ports:
      - "4000:8080"

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
  #      user: root
  #      password: example
  #      localhost: http://localhost:3306/ (?)

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"